name: Run Lichess Bot

on:
  workflow_dispatch:  # Кнопка "Run workflow"
  schedule:
    - cron: "*/15 * * * *"  # Запуск каждые 15 минут

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}                # ⬅️ Токен от lichess
      LICHESS_USERNAME: "Newchessengine-ai"      # ⬅️ Твоё имя
      MAX_GAMES: 3
      RATED: true                                 # true = рейтинг, false = обычная
      CHECK_INTERVAL: 15                         # секунд между проверками

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install berserk requests

      - name: Run Lichess Bot
        run: python bot.py
