name: Run Lichess Bot

on:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }}
      MAX_GAMES: 5  # можешь тут изменить

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install berserk requests

      - name: Run bot
        run: python bot.py
