name: Запуск бота

on:
  workflow_dispatch:  # запуск вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v3

      - name: Установка Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-chess

      - name: Сделать файл движка исполняемым
        run: chmod +x ./engines/SmileyMate.py

      - name: Запуск бота
        run: python user_interface.py
        env:
          TOKEN: ${{ secrets.TOKEN }}

